// Repli utilisé uniquement si NEXT_PUBLIC_PHARMACY_SERVICE_ID n'est pas défini.
export const PHARMACY_SERVICE_ID_FALLBACK = 'b0e542b2-4005-4518-bf75-37e6b39a2213';
export const PHARMACY_SERVICE_ID = process.env.NEXT_PUBLIC_PHARMACY_SERVICE_ID || PHARMACY_SERVICE_ID_FALLBACK;
