export { apiClient } from './client';
export { authService } from './auth.service';
export type { User, AuthResponse } from './auth.service';
export { patientService } from './patient.service';
export { medecinService } from './medecin.service';
export { notificationService } from './notification.service';
export { planningService } from './planning.service';
export { cpaService } from './cpa.service';
export { rapportsService } from './rapports.service';
export { pharmacieService } from './pharmacie.service';
